### ISSUE TITLE
Maximum posts limit

### ISSUE THREAD

**Issue by Jekamajor** [ScriptSmith/instaphyte#2]
Hello! 
When I try to get all posts from tag that have 40000+ posts, but 8000 posts only scrapped. It is possible to get all 40K posts? Why does python stops after 8K posts only (there is no any errors)? How can I make this limit bigger?
Thanks!

**Comment by ScriptSmith** [comment]
This is a problem with all instagram scraping tools, see instaloader/instaloader#55

In addition to what was said there, sometimes the number of posts able to be gathered is inconsistent, you might find that scraping again will gather fewer or more posts.
